"""
Pydantic schemas for Health Calculator Service
"""
from .health_calculator import (
    BMIRequest,
    BMIResponse,
    BMRRequest,
    BMRResponse,
    TDEERequest,
    TDEEResponse,
    BodyFatRequest,
    BodyFatResponse,
    WaistToHipRequest,
    WaistToHipResponse,
    WaistToHeightRequest,
    WaistToHeightResponse,
    IdealBodyWeightRequest,
    IdealBodyWeightResponse,
    BodySurfaceAreaRequest,
    BodySurfaceAreaResponse,
    MaxHeartRateRequest,
    MaxHeartRateResponse,
    TargetHeartRateRequest,
    TargetHeartRateResponse,
    MAPRequest,
    MAPResponse,
    MetabolicAgeRequest,
    MetabolicAgeResponse,
    DailyCalorieRequest,
    DailyCalorieResponse,
    MacronutrientsRequest,
    MacronutrientsResponse,
    OneRepMaxRequest,
    OneRepMaxResponse,
    CaloriesBurnedRequest,
    CaloriesBurnedResponse,
    VO2MaxRequest,
    VO2MaxResponse,
    RecoveryTimeRequest,
    RecoveryTimeResponse,
    WaterNeedsRequest,
    WaterNeedsResponse,
    BodyWaterRequest,
    BodyWaterResponse,
    HealthCalculationResponse,
    HealthMetricResponse
)

__all__ = [
    "BMIRequest", "BMIResponse",
    "BMRRequest", "BMRResponse",
    "TDEERequest", "TDEEResponse",
    "BodyFatRequest", "BodyFatResponse",
    "WaistToHipRequest", "WaistToHipResponse",
    "WaistToHeightRequest", "WaistToHeightResponse",
    "IdealBodyWeightRequest", "IdealBodyWeightResponse",
    "BodySurfaceAreaRequest", "BodySurfaceAreaResponse",
    "MaxHeartRateRequest", "MaxHeartRateResponse",
    "TargetHeartRateRequest", "TargetHeartRateResponse",
    "MAPRequest", "MAPResponse",
    "MetabolicAgeRequest", "MetabolicAgeResponse",
    "DailyCalorieRequest", "DailyCalorieResponse",
    "MacronutrientsRequest", "MacronutrientsResponse",
    "OneRepMaxRequest", "OneRepMaxResponse",
    "CaloriesBurnedRequest", "CaloriesBurnedResponse",
    "VO2MaxRequest", "VO2MaxResponse",
    "RecoveryTimeRequest", "RecoveryTimeResponse",
    "WaterNeedsRequest", "WaterNeedsResponse",
    "BodyWaterRequest", "BodyWaterResponse",
    "HealthCalculationResponse",
    "HealthMetricResponse"
]

